# Generated by Django 3.2.6 on 2021-08-27 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_category_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='kitob nomi')),
                ('author', models.CharField(max_length=255, verbose_name='muallif')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_need', to='categories.category', verbose_name='toifasi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_need', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kerakli Kitob',
                'verbose_name_plural': 'Kerakli Kitoblar 📚⬅️',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BookHave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='kitob nomi')),
                ('author', models.CharField(max_length=255, verbose_name='muallif')),
                ('image', models.ImageField(blank=True, upload_to='books/', verbose_name='kitob rasmini yuklash')),
                ('description', models.TextField(blank=True, verbose_name='tavsifi')),
                ('available', models.BooleanField(default=True, verbose_name='mavjud?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_have', to='categories.category', verbose_name='toifasi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_have', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mavjud Kitob',
                'verbose_name_plural': 'Mavjud Kitoblar 📚➡️',
                'ordering': ('name',),
            },
        ),
    ]
